FROM python:3.12-slim

WORKDIR /app/backend

COPY backend/pyproject.toml /app/backend/
RUN pip install --no-cache-dir poetry && poetry config virtualenvs.create false && poetry install --no-root --no-interaction --no-ansi

COPY backend /app/backend
COPY ml /app/ml
COPY .env.example /app/.env

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
