import { Song, Exercise, PracticePreset, ReferenceAudioType } from "../types";
import {
  REFERENCE_MELODIES,
  referencePitchSeqFromMelody,
  taskConfigFromReferenceMelody,
  pitchSeqToReferenceNotes,
} from "./referenceMelodies";

/** Build the reference block for a GTSinger preset from its pitch sequence. */
function gtsTaskConfig(
  technique: string,
  singer: string,
  title: string,
  skillFocus: string[],
  referencePitchSeq: number[],
  durationS = 30
) {
  const refNotes = pitchSeqToReferenceNotes(referencePitchSeq, durationS);
  return {
    task_type: "reference_song",
    target: null,
    reference: {
      type: "human_vocal_reference",
      source: "gtsinger",
      technique,
      singer,
      title,
      ...(refNotes ?? {}),
    },
    skill_focus: skillFocus,
    scoring_mode: refNotes ? "diagnostic" : "no_reference",
    strictness: "beginner",
  };
}

const makePracticeSong = (
  id: string,
  title: string,
  genre: string,
  duration: string,
  referencePitchSeq: number[],
  lyrics: string[] = [],
  referenceType: ReferenceAudioType = "synth_melody"
): Song => ({
  id,
  title,
  artist: "Guided Vocal Practice",
  genre,
  difficulty: "EASY",
  duration,
  bpm: 72,
  imageUrl: "https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=400&auto=format&fit=crop&q=80",
  lyrics: lyrics.length ? lyrics : ["Listen", "Breathe", "Sing", "Review"],
  referencePitchSeq,
  referenceType,
});

const HUMAN_PRACTICE_SONGS = {
  sustainedC4: makePracticeSong(
    "practice-sustained-c4",
    "Sustained C4",
    "Pitch Stability",
    "00:05",
    [50, 50, 50, 50, 50, 50],
    ["Hold a relaxed ah vowel on C4"],
    "generated_tone"
  ),
  noteMatchE4: makePracticeSong(
    "practice-note-match-e4",
    "Match E4",
    "Note Matching",
    "00:03",
    [42, 42, 42],
    ["Listen to E4, then sing one clear note"],
    "generated_tone"
  ),
  risingSlide: makePracticeSong(
    "practice-rising-slide",
    "Rising Siren 220-440",
    "Pitch Slide",
    "00:05",
    [70, 64, 58, 52, 46, 40],
    ["Glide up smoothly on an ah or oo vowel"],
    "generated_tone"
  ),
  majorScale: makePracticeSong(
    "practice-major-scale-c",
    "C Major Scale Fragment",
    "Scale",
    "00:08",
    referencePitchSeqFromMelody(REFERENCE_MELODIES.cMajorScale),
    ["Sing do re mi fa sol la ti do"],
    "synth_melody"
  ),
  majorThird: makePracticeSong(
    "practice-major-third-c-e",
    "Major Third C4-E4",
    "Interval",
    "00:03",
    referencePitchSeqFromMelody(REFERENCE_MELODIES.majorThird),
    ["Sing do then mi"],
    "synth_melody"
  ),
  twinkleOpening: makePracticeSong(
    "practice-twinkle-opening",
    "Twinkle Twinkle Opening",
    "Reference Melody",
    "00:08",
    referencePitchSeqFromMelody(REFERENCE_MELODIES.twinkleOpening),
    ["Twinkle twinkle little star"],
    "synth_melody"
  ),
  amazingGrace: makePracticeSong(
    "practice-amazing-grace-reference",
    "Amazing Grace Phrase",
    "Reference Melody",
    "00:12",
    referencePitchSeqFromMelody(REFERENCE_MELODIES.amazingGraceOpening),
    ["A short public-domain style phrase for reference-melody work"],
    "synth_melody"
  ),
  auldLangSyne: makePracticeSong(
    "practice-auld-lang-syne-opening",
    "Auld Lang Syne Opening",
    "Reference Melody",
    "00:08",
    referencePitchSeqFromMelody(REFERENCE_MELODIES.auldLangSyneOpening),
    ["Should auld acquaintance be forgot"],
    "synth_melody"
  ),
  freePhrase: makePracticeSong(
    "practice-free-vocal-phrase",
    "Free Vocal Phrase",
    "Free Singing",
    "00:15",
    [50, 50, 50, 50],
    ["Sing a short comfortable phrase"],
    "none"
  ),
};

// Canonical song objects for GTSinger technique presets.
// Referenced by identity from both PRACTICE_PRESETS and SONGS so that any
// runtime enrichment on one is immediately visible on the other.
const GTS_TECHNIQUE_SONGS = {
  memoryVibratoAlto1: {
    id: "gts-memory-vibrato-alto1",
    title: "Memory",
    artist: "GTSinger – EN-Alto-1 · Vibrato",
    genre: "Musical Theatre",
    difficulty: "MEDIUM" as const,
    duration: "00:30",
    bpm: 60,
    imageUrl: "https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=400&auto=format&fit=crop&q=80",
    lyrics: [] as string[],
    referencePitchSeq: [48, 50, 52, 55, 58, 60, 58, 55, 52, 50, 52, 55, 60, 63, 65, 63, 60, 55, 50, 48],
    referenceAudioUrl: "/api/audio/file?path=ml/data/raw/gtsinger/English/EN-Alto-1/Vibrato/memory/Control_Group/0000.wav",
    referenceStyle: "Vibrato – Female Alto",
    referenceType: "human_vocal" as const,
  },
  letItGoBreathyAlto1: {
    id: "gts-let-it-go-breathy-alto1",
    title: "Let It Go",
    artist: "GTSinger – EN-Alto-1 · Breathy",
    genre: "Animated Ballad",
    difficulty: "MEDIUM" as const,
    duration: "00:30",
    bpm: 65,
    imageUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&auto=format&fit=crop&q=80",
    lyrics: [] as string[],
    referencePitchSeq: [45, 48, 52, 55, 58, 60, 62, 65, 62, 60, 58, 55, 52, 48, 50, 55, 60, 62, 58, 52],
    referenceAudioUrl: "/api/audio/file?path=ml/data/raw/gtsinger/English/EN-Alto-1/Mixed_Voice_and_Falsetto/let it go/Control_Group/0000.wav",
    referenceStyle: "Breathy – Female Alto",
    referenceType: "human_vocal" as const,
  },
  laVieEnRoseMixedAlto1: {
    id: "gts-la-vie-en-rose-mixed-alto1",
    title: "La Vie en Rose",
    artist: "GTSinger – EN-Alto-1 · Mixed Voice",
    genre: "Classic Pop",
    difficulty: "HARD" as const,
    duration: "00:30",
    bpm: 70,
    imageUrl: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=400&auto=format&fit=crop&q=80",
    lyrics: [] as string[],
    referencePitchSeq: [50, 52, 55, 58, 62, 65, 68, 65, 62, 58, 55, 52, 55, 60, 65, 70, 68, 62, 55, 50],
    referenceAudioUrl: "/api/audio/file?path=ml/data/raw/gtsinger/English/EN-Alto-1/Mixed_Voice_and_Falsetto/la vie en rose/Control_Group/0000.wav",
    referenceStyle: "Mixed Voice & Falsetto – Female Alto",
    referenceType: "human_vocal" as const,
  },
  easyOnMeBreathyAlto2: {
    id: "gts-easy-on-me-breathy-alto2",
    title: "Easy On Me",
    artist: "GTSinger – EN-Alto-2 · Breathy",
    genre: "Pop Ballad",
    difficulty: "EASY" as const,
    duration: "00:30",
    bpm: 60,
    imageUrl: "https://images.unsplash.com/photo-1506157786151-b8491531f063?w=400&auto=format&fit=crop&q=80",
    lyrics: [] as string[],
    referencePitchSeq: [42, 45, 48, 52, 55, 52, 48, 45, 48, 52, 55, 58, 55, 52, 48, 50, 55, 58, 55, 50],
    referenceAudioUrl: "/api/audio/file?path=ml/data/raw/gtsinger/English/EN-Alto-2/Glissando/Easy On Me/Control_Group/0000.wav",
    referenceStyle: "Breathy – Female Alto",
    referenceType: "human_vocal" as const,
  },
  someoneYouLovedGlissandoAlto2: {
    id: "gts-someone-like-you-glissando-alto2",
    title: "Someone Like You",
    artist: "GTSinger – EN-Alto-2 · Glissando",
    genre: "Pop Ballad",
    difficulty: "HARD" as const,
    duration: "00:30",
    bpm: 67,
    imageUrl: "https://images.unsplash.com/photo-1571330735066-03aaa9429d89?w=400&auto=format&fit=crop&q=80",
    lyrics: [] as string[],
    referencePitchSeq: [48, 52, 55, 60, 58, 55, 52, 55, 60, 65, 62, 58, 55, 58, 62, 65, 68, 65, 60, 55],
    referenceAudioUrl: "/api/audio/file?path=ml/data/raw/gtsinger/English/EN-Alto-2/Glissando/Someone Like You/Control_Group/0000.wav",
    referenceStyle: "Glissando – Female Alto",
    referenceType: "human_vocal" as const,
  },
  alwaysRememberGlissandoTenor1: {
    id: "gts-always-remember-glissando-tenor1",
    title: "Always Remember Us This Way",
    artist: "GTSinger – EN-Tenor-1 · Glissando",
    genre: "Pop Ballad",
    difficulty: "HARD" as const,
    duration: "00:30",
    bpm: 68,
    imageUrl: "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=400&auto=format&fit=crop&q=80",
    lyrics: [] as string[],
    referencePitchSeq: [55, 58, 60, 63, 65, 63, 60, 58, 60, 63, 68, 72, 70, 65, 60, 58, 60, 65, 68, 63],
    referenceAudioUrl: "/api/audio/file?path=ml/data/raw/gtsinger/English/EN-Tenor-1/Glissando/Always Remember Us This Way/Control_Group/0000.wav",
    referenceStyle: "Glissando – Male Tenor",
    referenceType: "human_vocal" as const,
  },
  shallowMixedTenor1: {
    id: "gts-shallow-mixed-tenor1",
    title: "Shallow",
    artist: "GTSinger – EN-Tenor-1 · Mixed Voice",
    genre: "Pop Ballad",
    difficulty: "HARD" as const,
    duration: "00:30",
    bpm: 96,
    imageUrl: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=400&auto=format&fit=crop&q=80",
    lyrics: [] as string[],
    referencePitchSeq: [50, 53, 55, 58, 62, 65, 68, 65, 62, 58, 55, 52, 55, 58, 62, 68, 72, 70, 65, 58],
    referenceAudioUrl: "/api/audio/file?path=ml/data/raw/gtsinger/English/EN-Tenor-1/Mixed_Voice_and_Falsetto/Shallow/Control_Group/0000.wav",
    referenceStyle: "Mixed Voice & Falsetto – Male Tenor",
    referenceType: "human_vocal" as const,
  },
} satisfies Record<string, Song>;

export const PRACTICE_PRESETS: PracticePreset[] = [
  {
    id: "sustained-c4",
    title: "Sustained C4",
    description: "Hold one relaxed human vowel and review steadiness, drift, and dropouts.",
    category: "pitch",
    difficulty: "EASY",
    duration: "5s",
    source: "generated_reference",
    song: HUMAN_PRACTICE_SONGS.sustainedC4,
    taskConfig: {
      task_type: "sustained_note",
      target: { note: "C4", f0_hz: 261.63 },
      reference: { type: "generated_tone", note: "C4", f0_hz: 261.63 },
      skill_focus: ["pitch_stability", "voiced_continuity"],
      scoring_mode: "diagnostic",
      strictness: "beginner",
      expected_duration: 5,
    },
  },
  {
    id: "note-match-e4",
    title: "Match E4",
    description: "Hear one note, sing it back, and check cents error without full-song scoring.",
    category: "pitch",
    difficulty: "EASY",
    duration: "3s",
    source: "generated_reference",
    song: HUMAN_PRACTICE_SONGS.noteMatchE4,
    taskConfig: {
      task_type: "note_match",
      target: { note: "E4", f0_hz: 329.63 },
      reference: { type: "generated_tone", note: "E4", f0_hz: 329.63 },
      skill_focus: ["pitch_matching"],
      scoring_mode: "diagnostic",
      strictness: "beginner",
    },
  },
  {
    id: "rising-slide-220-440",
    title: "Rising Vocal Siren",
    description: "Glide from A3 toward A4; preserve human slide shape instead of note snapping.",
    category: "slide",
    difficulty: "EASY",
    duration: "5s",
    source: "generated_reference",
    song: HUMAN_PRACTICE_SONGS.risingSlide,
    taskConfig: {
      task_type: "pitch_slide",
      target: { start_f0_hz: 220, end_f0_hz: 440 },
      reference: { type: "generated_glide", start_f0_hz: 220, end_f0_hz: 440 },
      skill_focus: ["slide_smoothness", "continuity"],
      scoring_mode: "diagnostic",
      strictness: "beginner",
      expected_duration: 5,
      expected_direction: "up",
    },
  },
  {
    id: "c-major-scale-fragment",
    title: "C Major Scale Fragment",
    description: "A MIDI-style reference contour for scale practice and note movement review.",
    category: "scale",
    difficulty: "MEDIUM",
    duration: "8s",
    source: "midi_reference",
    song: HUMAN_PRACTICE_SONGS.majorScale,
    taskConfig: taskConfigFromReferenceMelody(REFERENCE_MELODIES.cMajorScale),
  },
  {
    id: "major-third-c4-e4",
    title: "Major Third Interval",
    description: "Sing a two-note jump used constantly in melodies: C4 to E4.",
    category: "scale",
    difficulty: "EASY",
    duration: "3s",
    source: "midi_reference",
    song: HUMAN_PRACTICE_SONGS.majorThird,
    taskConfig: taskConfigFromReferenceMelody(REFERENCE_MELODIES.majorThird),
  },
  {
    id: "twinkle-opening",
    title: "Twinkle Opening",
    description: "A familiar beginner melody for repeated notes, jumps, and stepwise descent.",
    category: "song",
    difficulty: "EASY",
    duration: "8s",
    source: "midi_reference",
    song: HUMAN_PRACTICE_SONGS.twinkleOpening,
    taskConfig: taskConfigFromReferenceMelody(REFERENCE_MELODIES.twinkleOpening),
  },
  {
    id: "amazing-grace-phrase",
    title: "Amazing Grace Phrase",
    description: "Public-domain melody reference for future reference-song alignment.",
    category: "song",
    difficulty: "MEDIUM",
    duration: "12s",
    source: "midi_reference",
    song: HUMAN_PRACTICE_SONGS.amazingGrace,
    taskConfig: taskConfigFromReferenceMelody(REFERENCE_MELODIES.amazingGraceOpening),
  },
  {
    id: "auld-lang-syne-opening",
    title: "Auld Lang Syne Opening",
    description: "Traditional phrase practice for gentle contour and phrase endings.",
    category: "song",
    difficulty: "EASY",
    duration: "8s",
    source: "midi_reference",
    song: HUMAN_PRACTICE_SONGS.auldLangSyne,
    taskConfig: taskConfigFromReferenceMelody(REFERENCE_MELODIES.auldLangSyneOpening),
  },
  // ── GTSinger human vocal reference presets ───────────────────────────────
  // These presets let the user hear a real human voice performing a technique,
  // then record themselves singing along. Scoring is reference_song (provisional).
  {
    id: "gts-vibrato-alto1-memory",
    title: "Vibrato: Memory (Alto)",
    description: "Listen to a female alto demonstrate vibrato on a sustained musical theatre phrase, then sing along.",
    category: "pitch",
    difficulty: "MEDIUM",
    duration: "30s",
    source: "dataset_reference",
    song: GTS_TECHNIQUE_SONGS.memoryVibratoAlto1,
    taskConfig: gtsTaskConfig("vibrato", "EN-Alto-1", "Memory", ["vibrato", "pitch_stability"], GTS_TECHNIQUE_SONGS.memoryVibratoAlto1.referencePitchSeq),
  },
  {
    id: "gts-breathy-alto1-let-it-go",
    title: "Breathy Tone: Let It Go (Alto)",
    description: "Listen to a female alto use breathy tone on this animated ballad phrase, then match the open, airy quality.",
    category: "pitch",
    difficulty: "MEDIUM",
    duration: "30s",
    source: "dataset_reference",
    song: GTS_TECHNIQUE_SONGS.letItGoBreathyAlto1,
    taskConfig: gtsTaskConfig("breathy", "EN-Alto-1", "Let It Go", ["breath_control", "tone_consistency"], GTS_TECHNIQUE_SONGS.letItGoBreathyAlto1.referencePitchSeq),
  },
  {
    id: "gts-mixed-alto1-la-vie-en-rose",
    title: "Mixed Voice: La Vie en Rose (Alto)",
    description: "Listen to a female alto blend chest and head voice on this classic phrase, then practice the register blend.",
    category: "pitch",
    difficulty: "HARD",
    duration: "30s",
    source: "dataset_reference",
    song: GTS_TECHNIQUE_SONGS.laVieEnRoseMixedAlto1,
    taskConfig: gtsTaskConfig("mixed_voice", "EN-Alto-1", "La Vie en Rose", ["register_blend", "pitch_stability"], GTS_TECHNIQUE_SONGS.laVieEnRoseMixedAlto1.referencePitchSeq),
  },
  {
    id: "gts-glissando-alto2-someone-like-you",
    title: "Glissando: Someone Like You (Alto)",
    description: "Listen to a female alto slide between notes on this pop ballad phrase, then match the glide accuracy.",
    category: "slide",
    difficulty: "HARD",
    duration: "30s",
    source: "dataset_reference",
    song: GTS_TECHNIQUE_SONGS.someoneYouLovedGlissandoAlto2,
    taskConfig: gtsTaskConfig("glissando", "EN-Alto-2", "Someone Like You", ["slide_smoothness", "pitch_accuracy"], GTS_TECHNIQUE_SONGS.someoneYouLovedGlissandoAlto2.referencePitchSeq),
  },
  {
    id: "gts-breathy-alto2-easy-on-me",
    title: "Breathy Tone: Easy On Me (Alto)",
    description: "Listen to the soft, breathy delivery on this Adele phrase, then match the open chest tone.",
    category: "pitch",
    difficulty: "EASY",
    duration: "30s",
    source: "dataset_reference",
    song: GTS_TECHNIQUE_SONGS.easyOnMeBreathyAlto2,
    taskConfig: gtsTaskConfig("breathy", "EN-Alto-2", "Easy On Me", ["breath_control", "onset_clarity"], GTS_TECHNIQUE_SONGS.easyOnMeBreathyAlto2.referencePitchSeq),
  },
  {
    id: "gts-glissando-tenor1-always-remember",
    title: "Glissando: Always Remember Us This Way (Tenor)",
    description: "Listen to a male tenor slide fluidly on this Lady Gaga phrase, then match the glide shape.",
    category: "slide",
    difficulty: "HARD",
    duration: "30s",
    source: "dataset_reference",
    song: GTS_TECHNIQUE_SONGS.alwaysRememberGlissandoTenor1,
    taskConfig: gtsTaskConfig("glissando", "EN-Tenor-1", "Always Remember Us This Way", ["slide_smoothness", "phrase_continuity"], GTS_TECHNIQUE_SONGS.alwaysRememberGlissandoTenor1.referencePitchSeq),
  },
  {
    id: "gts-mixed-tenor1-shallow",
    title: "Mixed Voice: Shallow (Tenor)",
    description: "Listen to a male tenor bridge chest and head voice on this A Star Is Born phrase, then practice the blend.",
    category: "pitch",
    difficulty: "HARD",
    duration: "30s",
    source: "dataset_reference",
    song: GTS_TECHNIQUE_SONGS.shallowMixedTenor1,
    taskConfig: gtsTaskConfig("mixed_voice", "EN-Tenor-1", "Shallow", ["register_blend", "pitch_accuracy"], GTS_TECHNIQUE_SONGS.shallowMixedTenor1.referencePitchSeq),
  },

  // ── Presets for the 5 original GTSinger SONGS entries ────────────────────
  // These were browsable in the song catalog but had no structured practice
  // preset until now. Songs are referenced from SONGS by id lookup at runtime
  // (see resolvePreset in improvementPath.ts); here we use inline refs to the
  // objects already defined later in SONGS to avoid duplication.
  {
    id: "gts-practice-a-thousand-years-vibrato",
    title: "Vibrato: A Thousand Years (Alto)",
    description: "Listen to EN-Alto-2 demonstrate vibrato on a slow, sustained pop ballad phrase, then match the steady oscillation.",
    category: "pitch",
    difficulty: "EASY",
    duration: "30s",
    source: "dataset_reference" as const,
    song: {
      id: "gts-a-thousand-years-vibrato",
      title: "A Thousand Years",
      artist: "GTSinger – EN-Alto-2 · Vibrato",
      genre: "Pop Ballad",
      difficulty: "EASY" as const,
      duration: "00:30",
      bpm: 68,
      imageUrl: "https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=400&auto=format&fit=crop&q=80",
      lyrics: [] as string[],
      referencePitchSeq: [50, 52, 55, 58, 60, 62, 60, 58, 55, 52, 50, 52, 55, 58, 62, 65, 62, 60, 55, 50],
      referenceAudioUrl: "/api/audio/file?path=ml/data/raw/gtsinger/English/EN-Alto-2/Vibrato/A Thousand Years/Vibrato_Group/0000.wav",
      referenceStyle: "Vibrato – Female Alto",
      referenceType: "human_vocal" as const,
    },
    taskConfig: gtsTaskConfig("vibrato", "EN-Alto-2", "A Thousand Years", ["vibrato", "pitch_stability"], [50, 52, 55, 58, 60, 62, 60, 58, 55, 52, 50, 52, 55, 58, 62, 65, 62, 60, 55, 50]),
  },
  {
    id: "gts-practice-shallow-breathy",
    title: "Breathy Tone: Shallow (Tenor)",
    description: "Listen to EN-Tenor-1 use breathy tone on this A Star Is Born phrase, then match the open, airy onset.",
    category: "pitch",
    difficulty: "MEDIUM",
    duration: "30s",
    source: "dataset_reference" as const,
    song: {
      id: "gts-shallow-breathy",
      title: "Shallow",
      artist: "GTSinger – EN-Tenor-1 · Breathy",
      genre: "Pop Ballad",
      difficulty: "MEDIUM" as const,
      duration: "00:30",
      bpm: 96,
      imageUrl: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=400&auto=format&fit=crop&q=80",
      lyrics: [] as string[],
      referencePitchSeq: [45, 48, 52, 55, 58, 62, 65, 62, 58, 55, 52, 48, 45, 48, 52, 58, 62, 68, 65, 60],
      referenceAudioUrl: "/api/audio/file?path=ml/data/raw/gtsinger/English/EN-Tenor-1/Mixed_Voice_and_Falsetto/Shallow/Control_Group/0000.wav",
      referenceStyle: "Breathy – Male Tenor",
      referenceType: "human_vocal" as const,
    },
    taskConfig: gtsTaskConfig("breathy", "EN-Tenor-1", "Shallow", ["breath_control", "onset_clarity"], [45, 48, 52, 55, 58, 62, 65, 62, 58, 55, 52, 48, 45, 48, 52, 58, 62, 68, 65, 60]),
  },
  {
    id: "gts-practice-rolling-glissando",
    title: "Glissando: Rolling in the Deep (Alto)",
    description: "Listen to EN-Alto-1 slide expressively through this Adele phrase, then match the glide shape.",
    category: "slide",
    difficulty: "HARD",
    duration: "30s",
    source: "dataset_reference" as const,
    song: {
      id: "gts-rolling-in-the-deep-glissando",
      title: "Rolling in the Deep",
      artist: "GTSinger – EN-Alto-1 · Glissando",
      genre: "Soul Pop",
      difficulty: "HARD" as const,
      duration: "00:30",
      bpm: 104,
      imageUrl: "https://images.unsplash.com/photo-1571330735066-03aaa9429d89?w=400&auto=format&fit=crop&q=80",
      lyrics: [] as string[],
      referencePitchSeq: [55, 58, 60, 62, 60, 58, 55, 52, 55, 58, 62, 65, 68, 65, 62, 58, 55, 52, 50, 48],
      referenceAudioUrl: "/api/audio/file?path=ml/data/raw/gtsinger/English/EN-Alto-1/Glissando/rolling in the deep/Control_Group/0000.wav",
      referenceStyle: "Glissando – Female Alto",
      referenceType: "human_vocal" as const,
    },
    taskConfig: gtsTaskConfig("glissando", "EN-Alto-1", "Rolling in the Deep", ["glissando", "slide_smoothness"], [55, 58, 60, 62, 60, 58, 55, 52, 55, 58, 62, 65, 68, 65, 62, 58, 55, 52, 50, 48]),
  },
  {
    id: "gts-practice-someone-like-you-vibrato",
    title: "Vibrato: Someone Like You (Tenor)",
    description: "Listen to EN-Tenor-1 develop natural vibrato on this Adele phrase, then let the oscillation develop on your held notes.",
    category: "pitch",
    difficulty: "MEDIUM",
    duration: "30s",
    source: "dataset_reference" as const,
    song: {
      id: "gts-someone-like-you-vibrato",
      title: "Someone Like You",
      artist: "GTSinger – EN-Tenor-1 · Vibrato",
      genre: "Pop Ballad",
      difficulty: "MEDIUM" as const,
      duration: "00:30",
      bpm: 67,
      imageUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&auto=format&fit=crop&q=80",
      lyrics: [] as string[],
      referencePitchSeq: [50, 52, 55, 58, 60, 60, 62, 58, 55, 52, 50, 52, 56, 60, 63, 65, 63, 60, 55, 50],
      referenceAudioUrl: "/api/audio/file?path=ml/data/raw/gtsinger/English/EN-Tenor-1/Vibrato/Someone Like You/Control_Group/0000.wav",
      referenceStyle: "Vibrato – Male Tenor",
      referenceType: "human_vocal" as const,
    },
    taskConfig: gtsTaskConfig("vibrato", "EN-Tenor-1", "Someone Like You", ["vibrato", "pitch_stability"], [50, 52, 55, 58, 60, 60, 62, 58, 55, 52, 50, 52, 56, 60, 63, 65, 63, 60, 55, 50]),
  },
  {
    id: "gts-practice-hello-mixed",
    title: "Mixed Voice: Hello (Alto)",
    description: "Listen to EN-Alto-2 blend chest and head voice on this Adele phrase, then practise smoothing the passaggio.",
    category: "pitch",
    difficulty: "HARD",
    duration: "30s",
    source: "dataset_reference" as const,
    song: {
      id: "gts-hello-mixed-voice",
      title: "Hello",
      artist: "GTSinger – EN-Alto-2 · Mixed Voice",
      genre: "Pop Ballad",
      difficulty: "HARD" as const,
      duration: "00:30",
      bpm: 76,
      imageUrl: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=400&auto=format&fit=crop&q=80",
      lyrics: [] as string[],
      referencePitchSeq: [48, 52, 55, 58, 62, 65, 68, 65, 62, 58, 55, 52, 55, 58, 62, 68, 72, 70, 65, 58],
      referenceAudioUrl: "/api/audio/file?path=ml/data/raw/gtsinger/English/EN-Alto-2/Mixed_Voice_and_Falsetto/Hello/Control_Group/0000.wav",
      referenceStyle: "Mixed Voice & Falsetto – Female Alto",
      referenceType: "human_vocal" as const,
    },
    taskConfig: gtsTaskConfig("mixed_voice", "EN-Alto-2", "Hello", ["register_blend", "pitch_stability"], [48, 52, 55, 58, 62, 65, 68, 65, 62, 58, 55, 52, 55, 58, 62, 68, 72, 70, 65, 58]),
  },

  {
    id: "free-human-phrase",
    title: "Free Human Vocal Phrase",
    description: "Sing a comfortable phrase and get safe no-reference feedback.",
    category: "free",
    difficulty: "EASY",
    duration: "15s",
    source: "generated_reference",
    song: HUMAN_PRACTICE_SONGS.freePhrase,
    taskConfig: {
      task_type: "free_singing",
      target: null,
      reference: null,
      skill_focus: ["general_pitch", "phrase_continuity"],
      scoring_mode: "no_reference",
      strictness: "beginner",
    },
  },

  // ── Preloaded VocalSet reference clips (bundled in samples/, no download needed) ──
  {
    id: "vs-forte-female",
    title: "Forte: Sustained A (Female)",
    description: "Listen to a professional female singer sustain a powerful forte tone, then match the volume and resonance.",
    category: "pitch",
    difficulty: "MEDIUM",
    duration: "11s",
    source: "dataset_reference" as const,
    song: {
      id: "vs-forte-female",
      title: "Forte Sustained A",
      artist: "VocalSet – Female Singer 1 · Forte",
      genre: "Vocal Exercise",
      difficulty: "MEDIUM" as const,
      duration: "00:11",
      bpm: 60,
      imageUrl: "",
      lyrics: [] as string[],
      referencePitchSeq: [],
      referenceAudioUrl: "/api/audio/file?path=samples/reference_vocals/vocalset/f1_long_forte_a.wav",
      referenceStyle: "Forte – Female",
      referenceType: "human_vocal" as const,
    },
    taskConfig: { task_type: "sustained_note", target: null, reference: null, skill_focus: ["volume_control", "tone_resonance"], scoring_mode: "no_reference", strictness: "beginner" },
  },
  {
    id: "vs-forte-male",
    title: "Forte: Sustained A (Male)",
    description: "Listen to a professional male singer sustain a powerful forte tone, then match the projection and breath support.",
    category: "pitch",
    difficulty: "MEDIUM",
    duration: "11s",
    source: "dataset_reference" as const,
    song: {
      id: "vs-forte-male",
      title: "Forte Sustained A",
      artist: "VocalSet – Male Singer 1 · Forte",
      genre: "Vocal Exercise",
      difficulty: "MEDIUM" as const,
      duration: "00:11",
      bpm: 60,
      imageUrl: "",
      lyrics: [] as string[],
      referencePitchSeq: [],
      referenceAudioUrl: "/api/audio/file?path=samples/reference_vocals/vocalset/m1_long_forte_a.wav",
      referenceStyle: "Forte – Male",
      referenceType: "human_vocal" as const,
    },
    taskConfig: { task_type: "sustained_note", target: null, reference: null, skill_focus: ["volume_control", "tone_resonance"], scoring_mode: "no_reference", strictness: "beginner" },
  },
  {
    id: "vs-pp-female",
    title: "Pianissimo: Soft Sustained A (Female)",
    description: "Listen to a professional female singer hold a pianissimo tone, then match the controlled softness without losing support.",
    category: "pitch",
    difficulty: "MEDIUM",
    duration: "11s",
    source: "dataset_reference" as const,
    song: {
      id: "vs-pp-female",
      title: "Pianissimo Sustained A",
      artist: "VocalSet – Female Singer 1 · Pianissimo",
      genre: "Vocal Exercise",
      difficulty: "MEDIUM" as const,
      duration: "00:11",
      bpm: 60,
      imageUrl: "",
      lyrics: [] as string[],
      referencePitchSeq: [],
      referenceAudioUrl: "/api/audio/file?path=samples/reference_vocals/vocalset/f1_long_pp_a.wav",
      referenceStyle: "Pianissimo – Female",
      referenceType: "human_vocal" as const,
    },
    taskConfig: { task_type: "sustained_note", target: null, reference: null, skill_focus: ["breath_control", "tone_consistency"], scoring_mode: "no_reference", strictness: "beginner" },
  },
  {
    id: "vs-pp-male",
    title: "Pianissimo: Soft Sustained A (Male)",
    description: "Listen to a professional male singer hold a pianissimo tone, then match the quiet, controlled resonance.",
    category: "pitch",
    difficulty: "MEDIUM",
    duration: "11s",
    source: "dataset_reference" as const,
    song: {
      id: "vs-pp-male",
      title: "Pianissimo Sustained A",
      artist: "VocalSet – Male Singer 1 · Pianissimo",
      genre: "Vocal Exercise",
      difficulty: "MEDIUM" as const,
      duration: "00:11",
      bpm: 60,
      imageUrl: "",
      lyrics: [] as string[],
      referencePitchSeq: [],
      referenceAudioUrl: "/api/audio/file?path=samples/reference_vocals/vocalset/m1_long_pp_a.wav",
      referenceStyle: "Pianissimo – Male",
      referenceType: "human_vocal" as const,
    },
    taskConfig: { task_type: "sustained_note", target: null, reference: null, skill_focus: ["breath_control", "tone_consistency"], scoring_mode: "no_reference", strictness: "beginner" },
  },
  {
    id: "vs-straight-female",
    title: "Straight Tone: Sustained A (Female)",
    description: "Listen to a clean, vibrato-free straight tone, then practise holding steady pitch without oscillation.",
    category: "pitch",
    difficulty: "EASY",
    duration: "11s",
    source: "dataset_reference" as const,
    song: {
      id: "vs-straight-female",
      title: "Straight Tone Sustained A",
      artist: "VocalSet – Female Singer 1 · Straight",
      genre: "Vocal Exercise",
      difficulty: "EASY" as const,
      duration: "00:11",
      bpm: 60,
      imageUrl: "",
      lyrics: [] as string[],
      referencePitchSeq: [],
      referenceAudioUrl: "/api/audio/file?path=samples/reference_vocals/vocalset/f1_long_straight_a.wav",
      referenceStyle: "Straight Tone – Female",
      referenceType: "human_vocal" as const,
    },
    taskConfig: { task_type: "sustained_note", target: null, reference: null, skill_focus: ["pitch_stability", "tone_consistency"], scoring_mode: "no_reference", strictness: "beginner" },
  },
  {
    id: "vs-vibrato-female",
    title: "Vibrato: Arpeggios (Female)",
    description: "Listen to natural vibrato on arpeggio phrases, then let the oscillation develop organically on your held notes.",
    category: "pitch",
    difficulty: "HARD",
    duration: "9s",
    source: "dataset_reference" as const,
    song: {
      id: "vs-vibrato-female",
      title: "Vibrato Arpeggios",
      artist: "VocalSet – Female Singer 1 · Vibrato",
      genre: "Vocal Exercise",
      difficulty: "HARD" as const,
      duration: "00:09",
      bpm: 80,
      imageUrl: "",
      lyrics: [] as string[],
      referencePitchSeq: [],
      referenceAudioUrl: "/api/audio/file?path=samples/reference_vocals/vocalset/f1_arpeggios_vibrato_u.wav",
      referenceStyle: "Vibrato – Female",
      referenceType: "human_vocal" as const,
    },
    taskConfig: { task_type: "sustained_note", target: null, reference: null, skill_focus: ["vibrato", "pitch_stability"], scoring_mode: "no_reference", strictness: "intermediate" },
  },
  {
    id: "vs-vibrato-male",
    title: "Vibrato: Arpeggios (Male)",
    description: "Listen to natural vibrato on arpeggio phrases from a male voice, then match the oscillation rate and depth.",
    category: "pitch",
    difficulty: "HARD",
    duration: "9s",
    source: "dataset_reference" as const,
    song: {
      id: "vs-vibrato-male",
      title: "Vibrato Arpeggios",
      artist: "VocalSet – Male Singer 1 · Vibrato",
      genre: "Vocal Exercise",
      difficulty: "HARD" as const,
      duration: "00:09",
      bpm: 80,
      imageUrl: "",
      lyrics: [] as string[],
      referencePitchSeq: [],
      referenceAudioUrl: "/api/audio/file?path=samples/reference_vocals/vocalset/m1_arpeggios_vibrato_u.wav",
      referenceStyle: "Vibrato – Male",
      referenceType: "human_vocal" as const,
    },
    taskConfig: { task_type: "sustained_note", target: null, reference: null, skill_focus: ["vibrato", "pitch_stability"], scoring_mode: "no_reference", strictness: "intermediate" },
  },
  {
    id: "vs-breathy-female",
    title: "Breathy Tone: Arpeggios (Female)",
    description: "Listen to a professional breathy tone on arpeggios, then match the airy onset and consistent airflow.",
    category: "pitch",
    difficulty: "MEDIUM",
    duration: "9s",
    source: "dataset_reference" as const,
    song: {
      id: "vs-breathy-female",
      title: "Breathy Arpeggios",
      artist: "VocalSet – Female Singer 1 · Breathy",
      genre: "Vocal Exercise",
      difficulty: "MEDIUM" as const,
      duration: "00:09",
      bpm: 80,
      imageUrl: "",
      lyrics: [] as string[],
      referencePitchSeq: [],
      referenceAudioUrl: "/api/audio/file?path=samples/reference_vocals/vocalset/f1_arpeggios_breathy_a.wav",
      referenceStyle: "Breathy – Female",
      referenceType: "human_vocal" as const,
    },
    taskConfig: { task_type: "sustained_note", target: null, reference: null, skill_focus: ["breath_control", "onset_clarity"], scoring_mode: "no_reference", strictness: "beginner" },
  },
];

export const SONGS: Song[] = [
  {
    id: "midnight-resonance",
    title: "Midnight Resonance",
    artist: "VocalStars Resident",
    genre: "Synth Wave",
    referenceType: "none",
    difficulty: "MEDIUM",
    duration: "03:15",
    bpm: 120,
    imageUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&auto=format&fit=crop&q=80",
    featured: true,
    lyrics: [
      "In the shadows of the neon light",
      "We are dancing through the deeper night",
      "Unleash your soulful resonance inside",
      "With the synthesizer as our guide",
      "Hold the note and let the feelings flow",
      "In the resonance of the midnight glow"
    ],
    referencePitchSeq: [50, 60, 48, 55, 62, 70, 65, 50, 42, 60, 55, 65, 70, 75, 62, 50, 45, 52, 60, 55]
  },
  {
    id: "electric-dreams",
    title: "Electric Dreams",
    artist: "Luna Ray",
    genre: "Synth Pop",
    referenceType: "none",
    difficulty: "EASY",
    duration: "02:50",
    bpm: 110,
    imageUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400&auto=format&fit=crop&q=80",
    lyrics: [
      "Electric pulses running through my mind",
      "A golden signal that is hard to find",
      "We build a dream inside a starry shell",
      "Under the power of a techno spell",
      "Come on and wake up now",
      "Let's make it real somehow"
    ],
    referencePitchSeq: [40, 40, 45, 50, 50, 45, 40, 55, 60, 60, 55, 50, 45, 45, 50, 55, 60, 50, 40, 40]
  },
  {
    id: "after-hours",
    title: "After Hours",
    artist: "The Night Sky",
    genre: "Retrowave",
    referenceType: "none",
    difficulty: "MEDIUM",
    duration: "03:40",
    bpm: 115,
    imageUrl: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=400&auto=format&fit=crop&q=80",
    lyrics: [
      "The sun went down an hour ago",
      "But we still have that inner spark inside",
      "Cruising past the city skylines slow",
      "In a dream where we don't have to hide",
      "Hold onto me, don't let it fade away",
      "We'll sing until the breaking of the day"
    ],
    referencePitchSeq: [30, 35, 45, 50, 42, 38, 50, 55, 65, 70, 58, 52, 65, 72, 80, 75, 62, 50, 45, 45]
  },
  {
    id: "unstoppable",
    title: "Unstoppable",
    artist: "Sia (Cover)",
    genre: "Pop Anthem",
    referenceType: "none",
    difficulty: "HARD",
    duration: "03:12",
    bpm: 125,
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuDxpI7FgU9FNUy001yzMNQfZdraRCuA1_acXoAJ8NUrnXYmioVldCg8BK25azx2I8Abj5_esb9GMn-tNTR_5JfBMrrtVcZzxlf-RonFh4r-OZwiQIYD5Tf5L8trBPPZ6AXqcAjeMpJhgnLeudnSjwaU7auCcnQKpJT4SAvDFIqwJkBX5pMImSJwOIcfL8VhRsVMgPJlHYTr-FTh1dUL8SdNjoVFyxmVI0nOb8oAZgj-gwuggiajNWWJ0XYwpe1-zTE7OazAbfOFzIpo",
    lyrics: [
      "I'm unstoppable, I'm a Porsche with no brakes",
      "I'm invincible, yeah, I win every single game",
      "I'm so powerful, I don't need batteries to play",
      "I'm so confident, yeah, I'm unstoppable today",
      "Break down the walls that hold you back tonight",
      "And lift your vocal power to the light"
    ],
    referencePitchSeq: [60, 65, 75, 70, 80, 82, 70, 60, 80, 85, 90, 85, 75, 65, 80, 85, 92, 88, 70, 65]
  },
  {
    id: "modern-soul",
    title: "Modern Soul",
    artist: "Echo Park",
    genre: "Soul & R&B",
    referenceType: "none",
    difficulty: "EASY",
    duration: "03:05",
    bpm: 95,
    imageUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&auto=format&fit=crop&q=80",
    lyrics: [
      "Walking down the old avenues of town",
      "Looking for a voice that doesn't put me down",
      "A modern soul is crying in the street",
      "Waiting for a rhythm to align the beat",
      "We have the key, we have the heart to sing",
      "Let's see the joy that music has to bring"
    ],
    referencePitchSeq: [45, 48, 52, 48, 55, 50, 45, 52, 58, 62, 55, 50, 58, 64, 68, 60, 52, 48, 45, 45]
  },
  {
    id: "frequency",
    title: "Frequency",
    artist: "Vibe Check",
    genre: "Electronic",
    referenceType: "none",
    difficulty: "MEDIUM",
    duration: "03:22",
    bpm: 124,
    imageUrl: "https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=400&auto=format&fit=crop&q=80",
    lyrics: [
      "Send your frequency into the empty wide",
      "There's no reason left for us to run and hide",
      "Can you feel the pulse inside your very shell?",
      "Every single wavelength weaving in a spell",
      "Hold the high notes, keep them clear and grand",
      "Across the echoes of this digital land"
    ],
    referencePitchSeq: [50, 55, 65, 58, 70, 72, 60, 50, 65, 70, 78, 72, 65, 55, 70, 75, 82, 78, 60, 55]
  },
  {
    id: "midnight-reverie",
    title: "Midnight Reverie",
    artist: "Luna Ray",
    genre: "Jazz Pop",
    referenceType: "none",
    difficulty: "MEDIUM",
    duration: "03:45",
    bpm: 124,
    imageUrl: "https://images.unsplash.com/photo-1487180142328-054b783fc471?w=400&auto=format&fit=crop&q=80",
    lyrics: [
      "I used to dream in shades of blue",
      "Before the stars aligned with you",
      "A symphony of quiet hearts",
      "Is where the magic really starts",
      "Hold your breath and count to three",
      "The world is ours, just you and me",
      "Singing our sweet, silent reverie"
    ],
    referencePitchSeq: [42, 45, 55, 60, 52, 48, 58, 62, 70, 75, 65, 55, 68, 72, 80, 85, 72, 60, 50, 48]
  },
  {
    id: "midnight-starlight",
    title: "Midnight Starlight",
    artist: "Nova Lyra",
    genre: "Dream Pop",
    referenceType: "none",
    difficulty: "EASY",
    duration: "02:55",
    bpm: 105,
    imageUrl: "https://images.unsplash.com/photo-1506157786151-b8491531f063?w=400&auto=format&fit=crop&q=80",
    lyrics: [
      "Can we dance under the midnight starlight glow?",
      "Forget the fears and let our heavy worries go",
      "A voice is whispering a melody so bright",
      "Guiding our spirits safely through the starry night",
      "Just hold the tone, let it sustain and shine",
      "A perfect frequency of your voice and mine"
    ],
    referencePitchSeq: [40, 42, 48, 52, 45, 42, 50, 55, 60, 65, 55, 48, 58, 62, 70, 72, 60, 50, 42, 40]
  },

  // ── GTSinger real vocal reference tracks ─────────────────────────────────
  // Audio served from the backend at /api/audio/file?path=...
  // lyrics[] are placeholders — the practice value is hearing the real voice.
  {
    id: "gts-a-thousand-years-vibrato",
    title: "A Thousand Years",
    artist: "GTSinger – EN-Alto-2 · Vibrato",
    genre: "Pop Ballad",
    difficulty: "EASY",
    duration: "00:30",
    bpm: 68,
    imageUrl: "https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=400&auto=format&fit=crop&q=80",
    featured: true,
    lyrics: ["Listen to the reference vocal", "Breathe and find the pitch", "Sing with vibrato on long notes", "Review your accuracy"],
    referencePitchSeq: [50, 52, 55, 58, 60, 62, 60, 58, 55, 52, 50, 52, 55, 58, 62, 65, 62, 60, 55, 50],
    referenceAudioUrl: "/api/audio/file?path=ml/data/raw/gtsinger/English/EN-Alto-2/Vibrato/A Thousand Years/Vibrato_Group/0000.wav",
    referenceStyle: "Vibrato – Female Alto",
    referenceType: "human_vocal",
  },
  {
    id: "gts-shallow-breathy",
    title: "Shallow",
    artist: "GTSinger – EN-Tenor-1 · Breathy",
    genre: "Pop Ballad",
    difficulty: "MEDIUM",
    duration: "00:30",
    bpm: 96,
    imageUrl: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=400&auto=format&fit=crop&q=80",
    lyrics: ["Listen to the breathy tone", "Match the phrase with an open chest", "Focus on smooth onset and release", "Check pitch accuracy"],
    referencePitchSeq: [45, 48, 52, 55, 58, 62, 65, 62, 58, 55, 52, 48, 45, 48, 52, 58, 62, 68, 65, 60],
    referenceAudioUrl: "/api/audio/file?path=ml/data/raw/gtsinger/English/EN-Tenor-1/Mixed_Voice_and_Falsetto/Shallow/Control_Group/0000.wav",
    referenceStyle: "Breathy – Male Tenor",
    referenceType: "human_vocal",
  },
  {
    id: "gts-rolling-in-the-deep-glissando",
    title: "Rolling in the Deep",
    artist: "GTSinger – EN-Alto-1 · Glissando",
    genre: "Soul Pop",
    difficulty: "HARD",
    duration: "00:30",
    bpm: 104,
    imageUrl: "https://images.unsplash.com/photo-1571330735066-03aaa9429d89?w=400&auto=format&fit=crop&q=80",
    lyrics: ["Listen for the slides between notes", "Match the glissando phrase", "Keep the chest voice grounded", "Review your glide accuracy"],
    referencePitchSeq: [55, 58, 60, 62, 60, 58, 55, 52, 55, 58, 62, 65, 68, 65, 62, 58, 55, 52, 50, 48],
    referenceAudioUrl: "/api/audio/file?path=ml/data/raw/gtsinger/English/EN-Alto-1/Glissando/rolling in the deep/Control_Group/0000.wav",
    referenceStyle: "Glissando – Female Alto",
    referenceType: "human_vocal",
  },
  {
    id: "gts-someone-like-you-vibrato",
    title: "Someone Like You",
    artist: "GTSinger – EN-Tenor-1 · Vibrato",
    genre: "Pop Ballad",
    difficulty: "MEDIUM",
    duration: "00:30",
    bpm: 67,
    imageUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&auto=format&fit=crop&q=80",
    lyrics: ["Listen to the vibrato phrasing", "Sing with a steady breath support", "Let the vibrato develop naturally on held notes", "Check stability"],
    referencePitchSeq: [50, 52, 55, 58, 60, 60, 62, 58, 55, 52, 50, 52, 56, 60, 63, 65, 63, 60, 55, 50],
    referenceAudioUrl: "/api/audio/file?path=ml/data/raw/gtsinger/English/EN-Tenor-1/Vibrato/Someone Like You/Control_Group/0000.wav",
    referenceStyle: "Vibrato – Male Tenor",
    referenceType: "human_vocal",
  },
  {
    id: "gts-hello-mixed-voice",
    title: "Hello",
    artist: "GTSinger – EN-Alto-2 · Mixed Voice",
    genre: "Pop Ballad",
    difficulty: "HARD",
    duration: "00:30",
    bpm: 76,
    imageUrl: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=400&auto=format&fit=crop&q=80",
    lyrics: ["Listen to the mixed voice blend", "Bridge chest and head voice smoothly", "Focus on the upper register phrase", "Review your register blend"],
    referencePitchSeq: [48, 52, 55, 58, 62, 65, 68, 65, 62, 58, 55, 52, 55, 58, 62, 68, 72, 70, 65, 58],
    referenceAudioUrl: "/api/audio/file?path=ml/data/raw/gtsinger/English/EN-Alto-2/Mixed_Voice_and_Falsetto/Hello/Control_Group/0000.wav",
    referenceStyle: "Mixed Voice & Falsetto – Female Alto",
    referenceType: "human_vocal",
  },

  // ── EN-Alto-1 (female alto) – remaining techniques ───────────────────────
  GTS_TECHNIQUE_SONGS.memoryVibratoAlto1,
  GTS_TECHNIQUE_SONGS.letItGoBreathyAlto1,
  GTS_TECHNIQUE_SONGS.laVieEnRoseMixedAlto1,
  {
    id: "gts-beauty-and-the-beast-pharyngeal-alto1",
    title: "Beauty and the Beast",
    artist: "GTSinger – EN-Alto-1 · Pharyngeal",
    genre: "Animated Ballad",
    difficulty: "MEDIUM",
    duration: "00:30",
    bpm: 70,
    imageUrl: "https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=400&auto=format&fit=crop&q=80",
    lyrics: [],
    referencePitchSeq: [48, 50, 52, 55, 58, 55, 52, 50, 52, 55, 58, 62, 60, 55, 52, 50, 52, 55, 58, 55],
    referenceAudioUrl: "/api/audio/file?path=ml/data/raw/gtsinger/English/EN-Alto-1/Pharyngeal/beauty and the beast/Control_Group/0000.wav",
    referenceStyle: "Pharyngeal – Female Alto",
    referenceType: "human_vocal",
  },

  // ── EN-Alto-2 (female alto) – additional techniques ──────────────────────
  GTS_TECHNIQUE_SONGS.easyOnMeBreathyAlto2,
  GTS_TECHNIQUE_SONGS.someoneYouLovedGlissandoAlto2,
  {
    id: "gts-all-of-me-pharyngeal-alto2",
    title: "All of Me",
    artist: "GTSinger – EN-Alto-2 · Pharyngeal",
    genre: "Pop Ballad",
    difficulty: "MEDIUM",
    duration: "00:30",
    bpm: 63,
    imageUrl: "https://images.unsplash.com/photo-1487180142328-054b783fc471?w=400&auto=format&fit=crop&q=80",
    lyrics: [],
    referencePitchSeq: [50, 52, 55, 58, 60, 58, 55, 52, 55, 58, 62, 65, 62, 58, 55, 52, 55, 58, 60, 55],
    referenceAudioUrl: "/api/audio/file?path=ml/data/raw/gtsinger/English/EN-Alto-2/Glissando/All of Me/Control_Group/0000.wav",
    referenceStyle: "Pharyngeal – Female Alto",
    referenceType: "human_vocal",
  },

  // ── EN-Tenor-1 (male tenor) – additional techniques ──────────────────────
  GTS_TECHNIQUE_SONGS.alwaysRememberGlissandoTenor1,
  GTS_TECHNIQUE_SONGS.shallowMixedTenor1,
  {
    id: "gts-someone-like-you-pharyngeal-tenor1",
    title: "Someone Like You",
    artist: "GTSinger – EN-Tenor-1 · Pharyngeal",
    genre: "Pop Ballad",
    difficulty: "MEDIUM",
    duration: "00:30",
    bpm: 67,
    imageUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&auto=format&fit=crop&q=80",
    lyrics: [],
    referencePitchSeq: [48, 50, 53, 55, 58, 55, 52, 50, 52, 55, 58, 62, 60, 55, 52, 50, 53, 57, 60, 55],
    referenceAudioUrl: "/api/audio/file?path=ml/data/raw/gtsinger/English/EN-Tenor-1/Vibrato/Someone Like You/Control_Group/0000.wav",
    referenceStyle: "Pharyngeal – Male Tenor",
    referenceType: "human_vocal",
  },
  {
    id: "gts-someone-you-loved-mixed-tenor1",
    title: "Someone You Loved",
    artist: "GTSinger – EN-Tenor-1 · Mixed Voice",
    genre: "Pop",
    difficulty: "MEDIUM",
    duration: "00:30",
    bpm: 110,
    imageUrl: "https://images.unsplash.com/photo-1487180142328-054b783fc471?w=400&auto=format&fit=crop&q=80",
    lyrics: [],
    referencePitchSeq: [52, 55, 58, 60, 62, 60, 58, 55, 58, 62, 65, 68, 65, 62, 58, 55, 58, 62, 65, 60],
    referenceAudioUrl: "/api/audio/file?path=ml/data/raw/gtsinger/English/EN-Alto-2/Glissando/Someone You Loved/Control_Group/0000.wav",
    referenceStyle: "Mixed Voice & Falsetto – Male Tenor",
    referenceType: "human_vocal",
  },
];

export const EXERCISES: Exercise[] = [
  {
    id: "breath-support",
    title: "Breath Support",
    description: "Hiss Exercise: Timed sustained exhales for core control.",
    duration: "5 MINS",
    type: "breath",
    difficulty: "EASY",
    progress: 33
  },
  {
    id: "pitch-resonance",
    title: "Pitch & Resonance",
    description: "Humming Scales, Lip Trills, and Straw Phonation.",
    duration: "8 MINS",
    type: "pitch",
    difficulty: "MEDIUM",
    progress: 50
  },
  {
    id: "agility-range",
    title: "Agility & Range",
    description: "Vocal Sirens, Vocal Glides, and Yawn-Sigh technique.",
    duration: "10 MINS",
    type: "agility",
    difficulty: "HARD",
    progress: 75
  },
  {
    id: "range-assessment",
    title: "Range Assessment",
    description: "Update your vocal profile with a smart dynamic diagnostic.",
    duration: "3 MINS",
    type: "assessment",
    difficulty: "MEDIUM",
    progress: 100
  }
];
